/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/audit/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 审计日志列表 */
        get: {
            parameters: {
                query?: {
                    /** @description 页码（默认 1） */
                    page?: number;
                    /** @description 每页条数（默认 20） */
                    page_size?: number;
                    /** @description 请求路径过滤 */
                    path?: string;
                    /** @description 用户 ID */
                    user_id?: number;
                    /** @description 开始日期（YYYY-MM-DD） */
                    start?: string;
                    /** @description 结束日期（YYYY-MM-DD） */
                    end?: string;
                    /** @description 工号 */
                    employee_no?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户登录 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 登录请求 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.LoginRequest"];
                };
            };
            responses: {
                /** @description 登录成功，返回 Token 对 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户登出 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 登出请求 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.LogoutRequest"];
                };
            };
            responses: {
                /** @description 登出成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 修改密码 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 修改密码请求 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.UpdatePasswordRequest"];
                };
            };
            responses: {
                /** @description 修改成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 刷新 Token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 刷新请求 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.RefreshRequest"];
                };
            };
            responses: {
                /** @description 刷新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dead-letters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 死信列表（运维向，配合 retry 端点闭环） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务定义列表（dept/action_id/enabled 过滤透传） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        put?: never;
        /** 新建任务定义（action_id + trigger_type + cron_spec + params） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
                /** @description cron_spec 非法等 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 手动执行一次任务定义（「立即执行」按钮） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description task_id + accepted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
                /** @description 定义已停用 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 修改任务定义（cron/params/启停；生效 ≤ 下个 cron tick） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 菜单树 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menus/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 菜单详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 菜单 ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/members/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 委托组成员名册（自服务，L3：owner/admin 或全局管理员可读）
         * @description 自服务名册（「我的组织」页消费）：与管理面 GET /orgs/:id/members 的区别——
         */
        get: {
            parameters: {
                query: {
                    /** @description 组织 ID */
                    org_id: string;
                    /** @description 页码 */
                    page?: number;
                    /** @description 每页条数 */
                    page_size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"] & {
                            data?: components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.OrgMemberRosterResponse"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/members/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 任命/变更组内角色 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 变更组内角色请求 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.SetOrgMemberRoleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/owners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 设置组织负责人 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 设置负责人请求 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.SetOrgOwnersRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/roles/bind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 组织绑定角色 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.BindOrgRoleRequest"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/roles/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 组织解绑角色 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.BindOrgRoleRequest"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/roles/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 组织已绑定角色列表 */
        get: {
            parameters: {
                query: {
                    /** @description 组织 ID */
                    org_id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 角色列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        put?: never;
        /** 创建角色 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 创建角色请求 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.CreateRoleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 删除角色 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 删除角色请求 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.RoleIDRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/menus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 分配角色菜单 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 分配菜单请求 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.AssignMenusRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 更新角色 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 更新角色请求 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.UpdateRoleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 角色详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 角色 ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/{id}/menus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询角色菜单 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 角色 ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/{id}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询角色权限 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 角色 ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查执行记录（request_id 跨查即此）
         * @description query 透传：request_id / action / status / job_id / from / to（RFC3339）
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 提交一次性任务（受理 ≠ 执行成功，结果经查询接口获取） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 提交参数（action 必填；callback_url 可缺省自动拼） */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_service.TaskSubmitInput"];
                };
            };
            responses: {
                /** @description task_id + accepted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
                /** @description taskrunner 未配置/不可达 */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 取消未开始的任务（执行中 409） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重试失败/死信任务 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查任务状态（job_runs 全景 + live_state 实时态）
         * @description 执行结果的唯一出口；taskrunner 不主动推送
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description task_id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ticket-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 工单模板列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        put?: never;
        /** 新建工单模板 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 模板定义 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.CreateTicketTemplateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ticket-templates/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 删除工单模板 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 模板编码 */
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ticket-templates/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 更新工单模板（patch；code/type/org 不可改） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 模板编码 */
                    code: string;
                };
                cookie?: never;
            };
            /** @description 更新内容 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.UpdateTicketTemplateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ticket-templates/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 工单模板详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 模板编码 */
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ticket-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 工单类型列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        put?: never;
        /** 新建工单类型 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 类型定义 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.CreateTicketTypeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ticket-types/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 删除工单类型（有工单禁删 → 409） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 类型编码 */
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ticket-types/fields/replace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 全量替换类型字段集 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 类型编码 */
                    code: string;
                };
                cookie?: never;
            };
            /** @description 字段集 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.ReplaceTypeFieldsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ticket-types/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 更新工单类型（patch；code 不可改） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 类型编码 */
                    code: string;
                };
                cookie?: never;
            };
            /** @description 更新内容 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.UpdateTicketTypeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ticket-types/{code}/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 工单类型字段定义 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 工单类型编码 */
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 工单列表 */
        get: {
            parameters: {
                query?: {
                    /** @description 页码 */
                    page?: number;
                    /** @description 每页条数 */
                    page_size?: number;
                    /** @description 工单类型 */
                    type_code?: string;
                    /** @description 工单状态 */
                    status?: string;
                    /** @description 处理人过滤，仅支持 me（当前用户——工作台待办/已办卡数据源） */
                    assignee?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        put?: never;
        /** 创建工单 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 创建工单请求 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.CreateTicketRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 分派工单 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 分派工单请求 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.AssignTicketRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 关闭工单 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 关闭工单请求 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.CloseTicketRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建工单回复 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 创建回复请求 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.CreateCommentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 删除工单 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 删除工单请求 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.DeleteTicketRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建内部备注 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 创建备注请求 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.CreateNoteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 建立工单关联 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 建立关联请求 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.CreateRelationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 更新工单 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 更新工单请求 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.UpdateTicketRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 工单详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 工单 ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 工单回复列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 工单 ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{id}/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 工单关联列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 工单 ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/menus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前用户菜单 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 我的组织列表（自服务：当前用户富化组织行——组织名/虚拟组/组内角色/数据范围）
         * @description 任何已认证用户可达（SelfService）；「我的组织」页数据源——
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"] & {
                            data?: components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.MyOrgsResponse"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前用户权限码 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前用户信息 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/profile/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 更新当前用户信息 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 更新个人信息请求 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.UpdateProfileRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 用户列表 */
        get: {
            parameters: {
                query?: {
                    /** @description 页码 */
                    page?: number;
                    /** @description 每页条数 */
                    page_size?: number;
                    /** @description 用户名 */
                    username?: string;
                    /** @description 工号 */
                    employee_no?: string;
                    /** @description 角色编码 */
                    role?: string;
                    /** @description 状态（1=启用 0=禁用） */
                    status?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        put?: never;
        /** 创建用户 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 创建用户请求 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.CreateUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 删除用户 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 删除用户请求 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.UserIDRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 设置用户所属组织 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 设置用户组织请求 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.SetUserOrgsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重置用户密码 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 重置密码请求 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.ResetPasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 设置用户角色 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 设置用户角色请求 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.SetUserRolesRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 启用/禁用用户 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 更新用户状态请求 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.UpdateUserStatusRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 更新用户 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 更新用户请求 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.UpdateUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 用户详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 用户 ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询用户所属组织 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 用户 ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/jobs/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 预置动作回调（taskrunner → zhuzhao，AK/SK 验签内网端点）
         * @description 结果映射（P6/P7）：2xx=执行完全成功/幂等受理；404=未知动作；409=不可重试；500=可重试
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.AssignMenusRequest": {
            menu_ids: number[];
            /** @example 0 */
            role_id: string;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.AssignTicketRequest": {
            /**
             * @description nil = 取消分派
             * @example 0
             */
            assigned_to?: string;
            /** @example 0 */
            id: string;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.BindOrgRoleRequest": {
            /** @example 0 */
            org_id: string;
            /** @example 0 */
            role_id: string;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.CloseTicketRequest": {
            /** @description 可选关闭说明 */
            comment?: string;
            /** @example 0 */
            id: string;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.CreateCommentRequest": {
            content: string;
            /** @example 0 */
            ticket_id: string;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.CreateNoteRequest": {
            content: string;
            /** @example 0 */
            ticket_id: string;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.CreateRelationRequest": {
            /** @description 默认 related */
            relation_type?: string;
            /** @example 0 */
            source_ticket_id: string;
            /** @example 0 */
            target_ticket_id: string;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.CreateRoleRequest": {
            code: string;
            description?: string;
            name: string;
            /**
             * @description BK-12：继承父（可选）。校验规则（2026-08-31 拍板）：child.priority ≤ parent.priority
             *     （子不弱于父）+ 父启用/非系统/无环/非自身
             * @example 0
             */
            parent_id?: string;
            priority: number;
            sort_order?: number;
            /**
             * @description B4-4：指针区分「未传」（nil → 默认启用）与「显式传 0」（创建即禁用）——
             *     原零值合并导致无法创建禁用角色，与 Update 的 oneof=0 1 行为不一致
             * @enum {integer}
             */
            status?: 0 | 1;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.CreateTicketRequest": {
            /** @example 0 */
            assigned_to?: string;
            custom_data?: number[];
            description?: string;
            /** @example 0 */
            org_id: string;
            priority?: number;
            /** @description 可选：命中模板则预填 */
            template_code?: string;
            title: string;
            type_code: string;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.CreateTicketTemplateRequest": {
            code: string;
            default_fields?: number[];
            default_priority?: number;
            default_sla_minutes?: number;
            name: string;
            /** @example 0 */
            org_id: string;
            type_code: string;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.CreateTicketTypeRequest": {
            code: string;
            description?: string;
            is_active?: boolean;
            name: string;
            states?: number[];
            transitions?: number[];
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.CreateUserRequest": {
            avatar?: string;
            domain_account?: string;
            email?: string;
            employee_no?: string;
            org_ids?: number[];
            /** @description F-9：最小长度（完整复杂度策略 Phase 2） */
            password: string;
            phone?: string;
            /** @example 0 */
            primary_org_id?: string;
            real_name?: string;
            role_ids?: number[];
            user_domain?: string;
            username: string;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.DeleteTicketRequest": {
            /** @example 0 */
            id: string;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.LoginRequest": {
            /** @description D2-01：max=64——device_id 进 RT JWT claims 与 Redis 键（refresh:{uid}:{device}） */
            device_id?: string;
            device_name?: string;
            /**
             * @description D2-01：max 对齐 DB varchar(50)——employee_no 直接进 Redis 锁定键
             *     （lock:login:{employee_no}），无上限时可灌入超大键撑爆 maxmemory 驱逐安全键
             */
            employee_no: string;
            password: string;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.LogoutRequest": {
            /** @description 与登录时一致；空则使用 default */
            device_id?: string;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.MyOrgItem": {
            is_primary?: boolean;
            is_virtual?: boolean;
            joined_at?: string;
            org_code?: string;
            /** @example 0 */
            org_id?: string;
            org_member_role?: string;
            org_name?: string;
            ticket_scope?: string;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.MyOrgsResponse": {
            list?: components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.MyOrgItem"][];
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.OrgMemberRosterItem": {
            avatar?: string;
            email?: string;
            employee_no?: string;
            is_primary?: boolean;
            /**
             * @description RFC3339（json 序列化 time.Time）——对齐仓内时间字段惯例；nullable schema 故
             *     指针+omitempty（检视 P1：曾用 PG ::text 输出空格分隔格式，Safari new Date 不可解析）
             */
            joined_at?: string;
            /** @description 组内角色（000013）：owner（仅 SetOwners 可设）/ admin / member */
            org_member_role?: string;
            phone?: string;
            real_name?: string;
            /** @description 1=启用 0=禁用 */
            status?: number;
            /** @description 数据范围（000012）：assigned / group / all */
            ticket_scope?: string;
            /** @example 0 */
            user_id?: string;
            username?: string;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.OrgMemberRosterResponse": {
            list?: components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.OrgMemberRosterItem"][];
            page?: number;
            page_size?: number;
            total?: number;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.RefreshRequest": {
            refresh_token: string;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.ReplaceTypeFieldsRequest": {
            /** @description W1（BK-18 整改）：code 从 path param 迁入 body */
            code: string;
            fields?: components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.TicketTypeFieldInput"][];
            /**
             * @description Version 可选乐观锁：以父类型 ticket_types.version 做 CAS；nil = 不做 CAS。
             *     须 > 0，否则 400。
             */
            version?: number;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.ResetPasswordRequest": {
            password: string;
            /** @example 0 */
            user_id: string;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.RoleIDRequest": {
            /** @example 0 */
            role_id: string;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.SetOrgMemberRoleRequest": {
            /** @example 0 */
            org_id: string;
            /** @enum {string} */
            org_member_role: "member" | "admin";
            /** @example 0 */
            user_id: string;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.SetOrgOwnersRequest": {
            /** @example 0 */
            org_id: string;
            /** @description 元素为字符串 ID（项目惯例）；空数组=清空（仅全局） */
            owner_user_ids: number[];
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.SetUserOrgsRequest": {
            org_ids?: number[];
            /** @example 0 */
            primary_org_id?: string;
            /** @example 0 */
            user_id: string;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.SetUserRolesRequest": {
            role_ids?: number[];
            /** @example 0 */
            user_id: string;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.TicketTypeFieldInput": {
            field_key: string;
            field_label: string;
            field_options?: number[];
            /** @enum {string} */
            field_type: "input" | "textarea" | "number" | "date" | "select" | "multi_select" | "tips";
            required?: boolean;
            sort_order?: number;
            validate_regex?: string;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.UpdatePasswordRequest": {
            /** @description 与登录时一致；空则使用 default */
            device_id?: string;
            new_password: string;
            old_password: string;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.UpdateProfileRequest": {
            avatar?: string;
            email?: string;
            phone?: string;
            real_name?: string;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.UpdateRoleRequest": {
            clear_parent?: boolean;
            description?: string;
            /** @example 0 */
            id: string;
            name: string;
            /**
             * @description BK-12：ParentID 显式变更（nil=保持现值）；ClearParent=true 清除继承
             * @example 0
             */
            parent_id?: string;
            priority: number;
            sort_order?: number;
            /** @enum {integer} */
            status?: 0 | 1;
            version: number;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.UpdateTicketRequest": {
            description?: string;
            /** @example 0 */
            id: string;
            priority?: number;
            title?: string;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.UpdateTicketTemplateRequest": {
            /** @description W1（BK-18 整改）：code 从 path param 迁入 body */
            code: string;
            default_fields?: number[];
            default_priority?: number;
            default_sla_minutes?: number;
            name?: string;
            /**
             * @description Version 可选乐观锁：nil = 不做 CAS（保持旧 patch 行为）；非 nil = 命中
             *     ticket_templates.version 才写，否则 409。须 > 0，否则 400。
             */
            version?: number;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.UpdateTicketTypeRequest": {
            /** @description W1（BK-18 整改）：code 从 path param 迁入 body（POST 风格，standards §3-2） */
            code: string;
            description?: string;
            is_active?: boolean;
            name?: string;
            states?: number[];
            transitions?: number[];
            /**
             * @description Version 可选乐观锁：nil = 不做 CAS（保持旧 patch 行为）；非 nil = 命中
             *     ticket_types.version 才写，否则 409。须 > 0，否则 400。
             */
            version?: number;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.UpdateUserRequest": {
            avatar?: string;
            domain_account?: string;
            email?: string;
            /** @description 指针字段：nil = 未传（保持原值），非 nil 空串 = 显式清空 */
            employee_no?: string;
            /** @example 0 */
            id: string;
            phone?: string;
            real_name?: string;
            user_domain?: string;
            version: number;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.UpdateUserStatusRequest": {
            /** @enum {integer} */
            status?: 0 | 1;
            /** @example 0 */
            user_id: string;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.UserIDRequest": {
            /** @example 0 */
            user_id: string;
        };
        "github_com_tracerbiubiubiu_zhuzhao_internal_service.TaskSubmitInput": {
            action: string;
            callback_url?: string;
            /** @description 一次性任务归属标签（E-⑤ 组装用户可见标签；C11 快照列） */
            dept?: string;
            params?: number[];
            /** @description 可选：调用方幂等键 */
            task_id?: string;
            timeout_secs?: number;
        };
        "response.Response": {
            code?: number;
            data?: unknown;
            message?: string;
            request_id?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: {
        /** @description 组织与角色 */
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.BindOrgRoleRequest": {
            content: {
                "application/json": components["schemas"]["github_com_tracerbiubiubiu_zhuzhao_internal_model.BindOrgRoleRequest"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
